---
- hosts: ws
  become: yes
  ignore_errors: yes
  tasks: 
    - name: Delete old artifact 
      file: 
        path: /opt/qa/spg/*.jar
        state: absent
    
    - name: Get the PID
      shell: lsof -t -i :8082
      register: pid_output
    
    - name: Kill running app
      shell: "kill -9 {{ pid_output.stdout }}"
      when : pid_output.stdout != ''
    
    - name: Download the new artifact
      get_url: 
        url: http://3.95.170.191:8081/artifactory/geolocation/geo/bio_8.jar
        dest: /opt/qa/spg 
        url_username: admin
        url_password: password

    - name: Name the app
      shell: nohup java -jar /opt/qa/spg/*.jar > /opt/qa/spg.log 2>&1 &