---
- hosts: ws
  become: yes
  ignore_errorvis: yes
  tasks: 
    - name: install packages
      yum: 
        state: present
        name: 
          - lsof
          - wget
          - passwd
          - docker
          - unzip
          - java-11*
    
    - name: create a directory 
      file:
        path: /opt/qa/spg
        state: directory
    
    - name: create a file 
      file:
        path: /opt/qa/spg/spg.log
        state: touch
      
    - name: start and enable docker 
      systemd:
        name: docker
        state: started
        enabled: yes


