---
- hosts: wind
  
  tasks:
    - name: Create a directory
      win_file:
        path: C:\Users\Administrator\Desktop\Manu
        state: directory
    
    - name: download file online
      win_get_url:
        dest: C:\Users\Administrator\Desktop\Manu
        url: https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.10.3.tar.xz
    
    - name: Update all packages
      win_updates:
        category_names: '*'
        reboot: true
