pipeline{
    agent any

    stages{

        stage("Create a zip file"){
            steps{
                sh 'zip ansible-dev${BUILD_ID}.zip * exclude Jenkinsfile'
            }
        }

        stage('Store in JFrog'){
            steps{
                sh 'curl -uadmin:AP6gCHaGvbw5kdFyGsCnMa2u4XR -T ansible-dev${BUILD_ID}.zip "http://52.86.210.117:8081/artifactory/ansible-project/ansible-dev${BUILD_ID}.zip"'
            }
        }
    }
}