pipeline{
    agent any

    stages{

        stage("Create a zip file"){
            steps{
                sh 'rm -rf *.zip || echo ""'
                sh 'zip -r ansible-dev${BUILD_ID}.zip * --exclude /script/Jenkinsfile'
                
            }
        }

        stage('Store in JFrog'){
            steps{
                sh 'curl -uadmin:AP6gCHaGvbw5kdFyGsCnMa2u4XR -T ansible-dev${BUILD_ID}.zip "http://3.95.170.191:8081/artifactory/ansible-project/ansible-dev${BUILD_ID}.zip"'
            }
        }

        stage('Publish to ansible server'){
            steps{
                sshPublisher(publishers: [sshPublisherDesc(configName: 'ansible', \
                transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: 'cd ~; cd /ansible-dev; unzip -o ansible-dev${BUILD_ID}.zip; rm -rf *.zip || echo ""', execTimeout: 120000, \
                flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '/ansible-dev', \
                remoteDirectorySDF: false, removePrefix: '', sourceFiles: 'ansible-dev${BUILD_ID}.zip')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
            }
        }
    }
}