pipeline{
    agent any

    stages{

        stage("Create a zip file"){
            steps{
                sh 'zip ansible-dev${BUILD_ID}.zip * --exclude /script/Jenkinsfile'
                sh 'ls -l script'
            }
        }

        stage('Store in JFrog'){
            steps{
                sh 'curl -uadmin:AP6gCHaGvbw5kdFyGsCnMa2u4XR -T ansible-dev${BUILD_ID}.zip "http://52.86.210.117:8081/artifactory/ansible-project/ansible-dev${BUILD_ID}.zip"'
            }
        }

        stage('Publish to ansible server'){
            steps{
                sshPublisher(publishers: [sshPublisherDesc(configName: 'ansible', transfers: \ 
                [sshTransfer(cleanRemote: false, excludes: '', execCommand: \
                'ls', execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '/home/ec2-user', \
                remoteDirectorySDF: false, removePrefix: '', sourceFiles: 'ansible-*.zip')], \
                usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
            }
        }
    }
}